import type { Product } from "@/types";

const img = (seed: string) =>
  `https://images.unsplash.com/${seed}?w=600&h=600&fit=crop&auto=format`;

function makeImages(seed: string): Product["images"] {
  return [
    { id: `${seed}-1`, url: img(seed), isThumbnail: true },
    { id: `${seed}-2`, url: img(seed), isThumbnail: false },
  ];
}

export const seedProducts: Product[] = [
  {
    id: "prod-1",
    name: "Samsung 990 Pro NVMe SSD 2TB PCIe 5.0",
    slug: "samsung-990-pro-2tb",
    sku: "SSD-SAM-990P-2TB",
    brandId: "brand-1",
    categoryId: "cat-ssd",
    description:
      "The 990 Pro delivers blistering PCIe 5.0 speeds for gaming, content creation, and professional workloads, backed by Samsung's in-house V-NAND and controller technology.",
    specifications: [
      { key: "Interface", value: "PCIe 5.0 NVMe" },
      { key: "Capacity", value: "2TB" },
      { key: "Read Speed", value: "7,450 MB/s" },
      { key: "Write Speed", value: "6,900 MB/s" },
      { key: "NAND", value: "Samsung V-NAND" },
      { key: "Warranty", value: "5 Years" },
    ],
    price: 2900000,
    discountPrice: 2450000,
    currency: "IDR",
    stock: 42,
    lowStockThreshold: 10,
    images: makeImages("photo-1597872200969-2b65d56bd16b"),
    featured: true,
    bestseller: true,
    newArrival: false,
    warranty: "5 Years",
    tags: ["ssd", "nvme", "pcie5", "gaming"],
    status: "active",
    createdAt: "2025-11-02T09:00:00Z",
    updatedAt: "2026-05-12T09:00:00Z",
  },
  {
    id: "prod-2",
    name: "Corsair Vengeance DDR5 32GB 6000MHz",
    slug: "corsair-vengeance-ddr5-32gb",
    sku: "RAM-COR-VEN5-32",
    brandId: "brand-6",
    categoryId: "cat-ram",
    description:
      "Vengeance DDR5 delivers high frequency performance with low latency timing for the newest generation of Intel and AMD platforms.",
    specifications: [
      { key: "Type", value: "DDR5 SDRAM" },
      { key: "Capacity", value: "32GB (2x16GB)" },
      { key: "Speed", value: "6000MHz" },
      { key: "CAS Latency", value: "CL36" },
      { key: "Voltage", value: "1.35V" },
      { key: "Warranty", value: "Lifetime" },
    ],
    price: 2200000,
    discountPrice: 1850000,
    currency: "IDR",
    stock: 67,
    lowStockThreshold: 15,
    images: makeImages("photo-1591488320449-011701bb6704"),
    featured: false,
    bestseller: true,
    newArrival: false,
    warranty: "Lifetime",
    tags: ["ram", "ddr5", "memory"],
    status: "active",
    createdAt: "2025-10-20T09:00:00Z",
    updatedAt: "2026-04-30T09:00:00Z",
  },
  {
    id: "prod-3",
    name: "ASUS ROG RTX 4070 Ti SUPER 16GB GDDR6X",
    slug: "asus-rog-rtx-4070-ti-super",
    sku: "GPU-ASU-4070TIS",
    brandId: "brand-7",
    categoryId: "cat-gpu",
    description:
      "ROG Strix RTX 4070 Ti SUPER brings flagship cooling and overclocking headroom to a 16GB GDDR6X graphics card built for 1440p and 4K gaming.",
    specifications: [
      { key: "GPU", value: "NVIDIA RTX 4070 Ti SUPER" },
      { key: "VRAM", value: "16GB GDDR6X" },
      { key: "Boost Clock", value: "2640 MHz" },
      { key: "TDP", value: "285W" },
      { key: "Ports", value: "3x DP 1.4, 2x HDMI 2.1" },
      { key: "Warranty", value: "3 Years" },
    ],
    price: 9500000,
    discountPrice: 8750000,
    currency: "IDR",
    stock: 6,
    lowStockThreshold: 8,
    images: makeImages("photo-1555617981-dac3880eac6e"),
    featured: true,
    bestseller: false,
    newArrival: true,
    warranty: "3 Years",
    tags: ["gpu", "rtx", "gaming"],
    status: "active",
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-06-10T09:00:00Z",
  },
  {
    id: "prod-4",
    name: "WD Black 4TB 7200RPM SATA HDD",
    slug: "wd-black-4tb-hdd",
    sku: "HDD-WD-BLK4TB",
    brandId: "brand-4",
    categoryId: "cat-hdd",
    description:
      "WD Black delivers high-capacity performance storage for gamers and creative professionals who need fast access to large game libraries and media files.",
    specifications: [
      { key: "Capacity", value: "4TB" },
      { key: "Interface", value: "SATA 6Gb/s" },
      { key: "RPM", value: "7200 RPM" },
      { key: "Cache", value: "256 MB" },
      { key: "Form Factor", value: "3.5\"" },
      { key: "Warranty", value: "5 Years" },
    ],
    price: 1100000,
    discountPrice: 890000,
    currency: "IDR",
    stock: 0,
    lowStockThreshold: 10,
    images: makeImages("photo-1616763355548-1b606f439f86"),
    featured: false,
    bestseller: true,
    newArrival: false,
    warranty: "5 Years",
    tags: ["hdd", "storage", "sata"],
    status: "active",
    createdAt: "2025-08-15T09:00:00Z",
    updatedAt: "2026-06-18T09:00:00Z",
  },
  {
    id: "prod-5",
    name: "Kingston KC3000 PCIe 4.0 NVMe SSD 1TB",
    slug: "kingston-kc3000-1tb",
    sku: "SSD-KIN-KC3000-1TB",
    brandId: "brand-2",
    categoryId: "cat-ssd",
    description:
      "KC3000 leverages a Gen 4x4 NVMe interface and 3D TLC NAND to deliver exceptional sequential read and write speeds for demanding applications.",
    specifications: [
      { key: "Interface", value: "PCIe 4.0 NVMe M.2" },
      { key: "Capacity", value: "1TB" },
      { key: "Read Speed", value: "7,000 MB/s" },
      { key: "Write Speed", value: "6,000 MB/s" },
      { key: "NAND", value: "3D TLC" },
      { key: "Warranty", value: "5 Years" },
    ],
    price: 1500000,
    discountPrice: 1250000,
    currency: "IDR",
    stock: 28,
    lowStockThreshold: 10,
    images: makeImages("photo-1593640408182-31c228f2a3a1"),
    featured: false,
    bestseller: false,
    newArrival: false,
    warranty: "5 Years",
    tags: ["ssd", "nvme"],
    status: "active",
    createdAt: "2025-09-05T09:00:00Z",
    updatedAt: "2026-05-01T09:00:00Z",
  },
  {
    id: "prod-6",
    name: "Intel Core i9-14900K Desktop Processor",
    slug: "intel-core-i9-14900k",
    sku: "CPU-INT-14900K",
    brandId: "brand-9",
    categoryId: "cat-cpu",
    description:
      "The Core i9-14900K pushes single-thread and multi-thread performance to new heights with 24 cores and boost clocks up to 6.0GHz.",
    specifications: [
      { key: "Cores", value: "24 (8P+16E)" },
      { key: "Threads", value: "32" },
      { key: "Base Clock", value: "3.2 GHz" },
      { key: "Boost Clock", value: "6.0 GHz" },
      { key: "TDP", value: "125W" },
      { key: "Socket", value: "LGA 1700" },
    ],
    price: 7500000,
    discountPrice: 6990000,
    currency: "IDR",
    stock: 19,
    lowStockThreshold: 10,
    images: makeImages("photo-1555617771-db6be1bc5f87"),
    featured: false,
    bestseller: true,
    newArrival: false,
    warranty: "3 Years",
    tags: ["cpu", "intel", "gaming"],
    status: "active",
    createdAt: "2025-11-20T09:00:00Z",
    updatedAt: "2026-06-05T09:00:00Z",
  },
  {
    id: "prod-7",
    name: "Crucial T500 Gen4 NVMe M.2 SSD 2TB",
    slug: "crucial-t500-2tb",
    sku: "SSD-CRU-T500-2TB",
    brandId: "brand-3",
    categoryId: "cat-ssd",
    description:
      "T500 combines Micron's latest 232-layer 3D NAND with a Gen4 controller for high sustained performance across everyday and creative workloads.",
    specifications: [
      { key: "Interface", value: "PCIe 4.0 NVMe" },
      { key: "Capacity", value: "2TB" },
      { key: "Read Speed", value: "7,400 MB/s" },
      { key: "Write Speed", value: "6,500 MB/s" },
      { key: "NAND", value: "Micron 232L 3D NAND" },
      { key: "Warranty", value: "5 Years" },
    ],
    price: 1980000,
    discountPrice: 1680000,
    currency: "IDR",
    stock: 33,
    lowStockThreshold: 10,
    images: makeImages("photo-1606318621004-6f1e9cc3c098"),
    featured: false,
    bestseller: false,
    newArrival: true,
    warranty: "5 Years",
    tags: ["ssd", "nvme"],
    status: "active",
    createdAt: "2026-02-14T09:00:00Z",
    updatedAt: "2026-06-01T09:00:00Z",
  },
  {
    id: "prod-8",
    name: "G.Skill Trident Z5 RGB DDR5 64GB Kit",
    slug: "gskill-trident-z5-64gb",
    sku: "RAM-GSK-TZ5-64",
    brandId: "brand-8",
    categoryId: "cat-ram",
    description:
      "Trident Z5 RGB pairs striking customizable lighting with high-frequency DDR5 performance, designed and tested for the latest Intel and AMD platforms.",
    specifications: [
      { key: "Type", value: "DDR5" },
      { key: "Capacity", value: "64GB (2x32GB)" },
      { key: "Speed", value: "6400MHz" },
      { key: "CAS Latency", value: "CL32" },
      { key: "RGB", value: "Yes" },
      { key: "Warranty", value: "Lifetime" },
    ],
    price: 3800000,
    discountPrice: 3200000,
    currency: "IDR",
    stock: 4,
    lowStockThreshold: 8,
    images: makeImages("photo-1591488320449-011701bb6704"),
    featured: false,
    bestseller: false,
    newArrival: true,
    warranty: "Lifetime",
    tags: ["ram", "ddr5", "rgb"],
    status: "active",
    createdAt: "2026-03-18T09:00:00Z",
    updatedAt: "2026-06-15T09:00:00Z",
  },
  {
    id: "prod-9",
    name: "Seagate BarraCuda SSD 1TB SATA",
    slug: "seagate-barracuda-1tb",
    sku: "SSD-SEA-BC-1TB",
    brandId: "brand-5",
    categoryId: "cat-ssd",
    description:
      "BarraCuda SATA SSD offers a reliable, affordable upgrade path from hard drives with consistent everyday performance.",
    specifications: [
      { key: "Interface", value: "SATA 6Gb/s" },
      { key: "Capacity", value: "1TB" },
      { key: "Read Speed", value: "560 MB/s" },
      { key: "Write Speed", value: "540 MB/s" },
      { key: "Form Factor", value: "2.5\"" },
      { key: "Warranty", value: "5 Years" },
    ],
    price: 750000,
    discountPrice: 480000,
    currency: "IDR",
    stock: 51,
    lowStockThreshold: 15,
    images: makeImages("photo-1593640408182-31c228f2a3a1"),
    featured: false,
    bestseller: false,
    newArrival: false,
    warranty: "5 Years",
    tags: ["ssd", "sata", "budget"],
    status: "active",
    createdAt: "2025-07-01T09:00:00Z",
    updatedAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "prod-10",
    name: "Kingston DataTraveler USB 3.2 256GB",
    slug: "kingston-datatraveler-256gb",
    sku: "USB-KIN-DT-256",
    brandId: "brand-2",
    categoryId: "cat-usb",
    description:
      "A compact, durable metal-bodied flash drive offering fast USB 3.2 transfer speeds for everyday file transport.",
    specifications: [
      { key: "Interface", value: "USB 3.2 Gen 1" },
      { key: "Capacity", value: "256GB" },
      { key: "Read Speed", value: "200 MB/s" },
      { key: "Design", value: "Compact Metal" },
      { key: "Compatibility", value: "USB-A" },
      { key: "Warranty", value: "5 Years" },
    ],
    price: 220000,
    discountPrice: 159000,
    currency: "IDR",
    stock: 124,
    lowStockThreshold: 30,
    images: makeImages("photo-1627328561499-a3584d4ee4f7"),
    featured: false,
    bestseller: true,
    newArrival: false,
    warranty: "5 Years",
    tags: ["usb", "flash", "portable"],
    status: "active",
    createdAt: "2025-06-12T09:00:00Z",
    updatedAt: "2026-03-22T09:00:00Z",
  },
  {
    id: "prod-11",
    name: "ASUS ROG Strix Z790-E Gaming Motherboard",
    slug: "asus-rog-strix-z790-e",
    sku: "MB-ASU-Z790E",
    brandId: "brand-7",
    categoryId: "cat-mobo",
    description:
      "Strix Z790-E delivers robust power delivery, PCIe 5.0 connectivity, and premium cooling for high-end Intel builds.",
    specifications: [
      { key: "Socket", value: "LGA 1700" },
      { key: "Chipset", value: "Intel Z790" },
      { key: "Memory", value: "DDR5 up to 7800MHz" },
      { key: "PCIe", value: "PCIe 5.0 x16" },
      { key: "Form Factor", value: "ATX" },
      { key: "Warranty", value: "3 Years" },
    ],
    price: 5990000,
    discountPrice: 5490000,
    currency: "IDR",
    stock: 11,
    lowStockThreshold: 8,
    images: makeImages("photo-1518770660439-4636190af475"),
    featured: true,
    bestseller: false,
    newArrival: true,
    warranty: "3 Years",
    tags: ["motherboard", "intel", "gaming"],
    status: "active",
    createdAt: "2026-01-08T09:00:00Z",
    updatedAt: "2026-05-29T09:00:00Z",
  },
  {
    id: "prod-12",
    name: "Toshiba Canvio 2TB External HDD USB",
    slug: "toshiba-canvio-2tb",
    sku: "EXT-TOS-CAN-2TB",
    brandId: "brand-12",
    categoryId: "cat-ext",
    description:
      "A slim, portable external drive offering 2TB of plug-and-play storage compatible with both PC and Mac.",
    specifications: [
      { key: "Capacity", value: "2TB" },
      { key: "Interface", value: "USB 3.2" },
      { key: "RPM", value: "5400 RPM" },
      { key: "Form Factor", value: "2.5\" Portable" },
      { key: "Compatibility", value: "PC / Mac" },
      { key: "Warranty", value: "2 Years" },
    ],
    price: 780000,
    discountPrice: 520000,
    currency: "IDR",
    stock: 9,
    lowStockThreshold: 10,
    images: makeImages("photo-1616763355548-1b606f439f86"),
    featured: false,
    bestseller: false,
    newArrival: false,
    warranty: "2 Years",
    tags: ["external", "portable", "storage"],
    status: "hidden",
    createdAt: "2025-05-20T09:00:00Z",
    updatedAt: "2026-02-11T09:00:00Z",
  },
];
